#! python


def build(ctx):

    ctx(
        features='run_do_script',
        source='generate_data.do',
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'generate_data.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'data_gen.dta')
        ]
    )
