#! python


def build(ctx):
    
    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)


    ctx(
        features='run_do_script',
        source='generate_data.do',
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'generate_data.log'),
            ctx.path_to(ctx, 'OUT_DATA', 'source_data', 'data_gen.dta')
        ]
    )

    ctx(
	features='run_do_script',
        source='data_management.do',
        target=[
            ctx.path_to(ctx, 'OUT_DATA', 'log', 'data_management.log'),
	    ctx.path_to(ctx, 'OUT_DATA', 'tables', 'data_table_1.dta'),
	    ctx.path_to(ctx, 'OUT_DATA', 'tables', 'data_table_2.dta'),
	    ctx.path_to(ctx, 'OUT_DATA', 'tables', 'data_table_3.dta')
        ],
	deps=[out_data('source_data', 'data_gen.dta')]
    )
 
    ctx(
	features='run_py_script',
	source='merge_data.py',
	deps=[
	     out_data('tables', 'data_table_1.dta'),
	     out_data('tables', 'data_table_2.dta'),
	     out_data('tables', 'data_table_3.dta')
	],
	target=[
            ctx.path_to(ctx, 'OUT_DATA', 'data_all.csv')
	],
	name='merge_data'
    )










    