#! python


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_figures(*args):
        return ctx.path_to(ctx, 'OUT_FIGURES', *args)

    def out_tables(*args):
        return ctx.path_to(ctx, 'OUT_TABLES', *args)

    ctx(
        features='run_py_script',
        source='plot_differences.py',
        target=[
out_figures('boxplot_fac1.png'),
out_figures('boxplot_fac2.png'),
            out_figures('boxplot_fac3.png')
        ],
        deps=[
                out_analysis('factor_estimates.pkl'),
                out_analysis('true_facs.pkl')
            ]
    )

