#! python


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_figures(*args):
        return ctx.path_to(ctx, 'OUT_FIGURES', *args)

    def out_tables(*args):
        return ctx.path_to(ctx, 'OUT_TABLES', *args)
    
    for prior in 'rnd_prior', 'deg_prior':
        ctx(
            features = 'run_py_script',
            source = 'plot_differences.py',
            target = [
                        out_figures('{}_boxplot_fac1.png'.format(prior)),
                        out_figures('{}_boxplot_fac2.png'.format(prior)),
                        out_figures('{}_boxplot_fac3.png'.format(prior))
                     ],
            deps = [
                    out_analysis('{}_factor_estimates.pkl'.format(prior)),
                    out_analysis('true_facs.pkl')
                   ],
            append = prior,
            name = 'plot_differences_{}'.format(prior)
        )
        
        ctx(
            features = 'run_py_script',
            source = 'summary_stats.py',
            target = [
                        out_tables('{}_est_bias.csv'.format(prior)),
                        out_tables('{}_est_rmse.csv'.format(prior))
                     ],
            deps = [
                    out_analysis('{}_factor_estimates.pkl'.format(prior)),
                    out_analysis('true_facs.pkl')
                   ],
            append = prior,
            name = 'summary_stats_{}'.format(prior)
        )

