#! python


def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_figures(*args):
        return ctx.path_to(ctx, 'OUT_FIGURES', *args)

    def out_tables(*args):
        return ctx.path_to(ctx, 'OUT_TABLES', *args)
    
    for spec in 'rnd_prior', 'deg_prior':
        ctx(
            features = 'run_py_script',
            source = 'plot_differences.py',
            target = [
                        out_figures('{}_boxplot_fac1.png'.format(spec)),
                        out_figures('{}_boxplot_fac2.png'.format(spec)),
                        out_figures('{}_boxplot_fac3.png'.format(spec))
                     ],
            deps = [
                    out_analysis('{}_factor_estimates.pkl'.format(spec)),
                    out_analysis('true_facs.pkl')
                   ],
            append = spec,
            name = 'plot_differences_{}'.format(spec)
        )

