#! python





def build(ctx):

    def out_data(*args):
        return ctx.path_to(ctx, 'OUT_DATA', *args)

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)
    
    ctx(
        features = 'run_py_script',
        source = 'prepare_data.py',
        target = [
                    out_analysis('meas_fac1.pkl'),
                    out_analysis('meas_fac2.pkl'),
                    out_analysis('meas_fac3.pkl')
                 ]
        #deps=[
        #         out_data('tables','data_table_1.dta'),
        #         out_data('tables','data_table_2.dta'),
       #          out_data('tables','data_table_3.dta')
        #    ]
    )

    ctx(
        features='run_py_script',
        source='particle_smoother.py',
        target=[
            out_analysis('log', 'particle_smoother.log')
        ],
        deps = [
                    out_analysis('meas_fac1.pkl'),
                    out_analysis('meas_fac2.pkl'),
                    out_analysis('meas_fac3.pkl')
               ]
    )

   
