#! python





def build(ctx):

    def out_models(*args):
        return ctx.path_to(ctx, 'OUT_MODEL_SPECS', *args)

    def out_analysis(*args):
        return ctx.path_to(ctx, 'OUT_ANALYSIS', *args)

    ctx(
        features='run_py_script',
        source='samples_from_prior.py',
        target=[
	    out_analysis('samples_from_prior.pickle'),
        ],
	deps=[
	    ctx.path_to(ctx, 'IN_MODEL_SPECS', 'true_prior.json')
        ]
    )

   
